[build-system]
requires = ["setuptools", "setuptools_scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "odyss_ai_flows"
version = "0.4.0"
authors = [
    { name = "Aleksander Bydlowski", email = "ai@bydlow.ski" }
]
requires-python = ">=3.11"

dependencies = [
    "jinja2",
    "networkx",
    "python-dotenv",
    "pydantic",
]

[project.optional-dependencies]
azure = ["odyss_ai_flows_azure"]

[project.scripts]
odyss = "odyss_ai_flows.cli:main"

[tool.setuptools.packages.find]
include = ["odyss_ai_flows*"]

[tool.setuptools.package-data]
"odyss_ai_flows._starter_templates" = [
    "*.md",
    "*.txt",
    "*.json",
    "flow/*.txt",
    "flow/*.json",
    "flow/*.jinja2",
]
