SHARED_EXECUTIONS = 0

DYNAMIC_A_EXECUTIONS = 0

DYNAMIC_B_EXECUTIONS = 0


SHARED_OBJECT = object()


def reset_state():

    global SHARED_EXECUTIONS
    global DYNAMIC_A_EXECUTIONS
    global DYNAMIC_B_EXECUTIONS

    SHARED_EXECUTIONS = 0
    DYNAMIC_A_EXECUTIONS = 0
    DYNAMIC_B_EXECUTIONS = 0